run:
  timeout: 5m
  skip-dirs:
    - internal/render
linters-settings:
  staticcheck:
    go: 1.16
  stylecheck:
    go: 1.16
  govet:
    disable:
      - fieldalignment
    check-shadowing: true
    enable-all: true
  cyclop:
    max-complexity: 24
  gci:
    local-prefixes: github.com/limpidchart
  goimports:
    local-prefixes: github.com/limpidchart
linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - asciicheck
    - bodyclose
    - cyclop
    - depguard
    - dogsled
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - ifshort
    - importas
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
