// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: renderer_service.proto

package render

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RenderChartRequest represents chart rendering request.
type RenderChartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID of the request.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Chart title.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Configured chart sizes.
	Sizes *ChartSizes `protobuf:"bytes,3,opt,name=sizes,proto3" json:"sizes,omitempty"`
	// Configured chart margins.
	Margins *ChartMargins `protobuf:"bytes,4,opt,name=margins,proto3" json:"margins,omitempty"`
	// Configured chart axes.
	Axes *ChartAxes `protobuf:"bytes,5,opt,name=axes,proto3" json:"axes,omitempty"`
	// Configured chart views.
	Views []*ChartView `protobuf:"bytes,6,rep,name=views,proto3" json:"views,omitempty"`
}

func (x *RenderChartRequest) Reset() {
	*x = RenderChartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_renderer_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderChartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderChartRequest) ProtoMessage() {}

func (x *RenderChartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_renderer_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderChartRequest.ProtoReflect.Descriptor instead.
func (*RenderChartRequest) Descriptor() ([]byte, []int) {
	return file_renderer_service_proto_rawDescGZIP(), []int{0}
}

func (x *RenderChartRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RenderChartRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RenderChartRequest) GetSizes() *ChartSizes {
	if x != nil {
		return x.Sizes
	}
	return nil
}

func (x *RenderChartRequest) GetMargins() *ChartMargins {
	if x != nil {
		return x.Margins
	}
	return nil
}

func (x *RenderChartRequest) GetAxes() *ChartAxes {
	if x != nil {
		return x.Axes
	}
	return nil
}

func (x *RenderChartRequest) GetViews() []*ChartView {
	if x != nil {
		return x.Views
	}
	return nil
}

// RenderChartReply represents chart rendering reply.
type RenderChartReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID of the request.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Chart raw bytes representation.
	ChartData []byte `protobuf:"bytes,2,opt,name=chart_data,json=chartData,proto3" json:"chart_data,omitempty"`
}

func (x *RenderChartReply) Reset() {
	*x = RenderChartReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_renderer_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderChartReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderChartReply) ProtoMessage() {}

func (x *RenderChartReply) ProtoReflect() protoreflect.Message {
	mi := &file_renderer_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderChartReply.ProtoReflect.Descriptor instead.
func (*RenderChartReply) Descriptor() ([]byte, []int) {
	return file_renderer_service_proto_rawDescGZIP(), []int{1}
}

func (x *RenderChartReply) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RenderChartReply) GetChartData() []byte {
	if x != nil {
		return x.ChartData
	}
	return nil
}

var File_renderer_service_proto protoreflect.FileDescriptor

var file_renderer_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x1a, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x76,
	0x69, 0x65, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf3, 0x01, 0x0a, 0x12, 0x52, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x68,
	0x61, 0x72, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x73, 0x52, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x12,
	0x2e, 0x0a, 0x07, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x74, 0x4d,
	0x61, 0x72, 0x67, 0x69, 0x6e, 0x73, 0x52, 0x07, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x73, 0x12,
	0x25, 0x0a, 0x04, 0x61, 0x78, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x74, 0x41, 0x78, 0x65, 0x73,
	0x52, 0x04, 0x61, 0x78, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x43,
	0x68, 0x61, 0x72, 0x74, 0x56, 0x69, 0x65, 0x77, 0x52, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x22,
	0x50, 0x0a, 0x10, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x32, 0x56, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x65, 0x72, 0x12, 0x45, 0x0a, 0x0b, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72,
	0x74, 0x12, 0x1a, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x6d, 0x70, 0x69, 0x64, 0x63, 0x68,
	0x61, 0x72, 0x74, 0x2f, 0x6c, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x2f, 0x76, 0x30, 0x3b, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_renderer_service_proto_rawDescOnce sync.Once
	file_renderer_service_proto_rawDescData = file_renderer_service_proto_rawDesc
)

func file_renderer_service_proto_rawDescGZIP() []byte {
	file_renderer_service_proto_rawDescOnce.Do(func() {
		file_renderer_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_renderer_service_proto_rawDescData)
	})
	return file_renderer_service_proto_rawDescData
}

var file_renderer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_renderer_service_proto_goTypes = []interface{}{
	(*RenderChartRequest)(nil), // 0: render.RenderChartRequest
	(*RenderChartReply)(nil),   // 1: render.RenderChartReply
	(*ChartSizes)(nil),         // 2: render.ChartSizes
	(*ChartMargins)(nil),       // 3: render.ChartMargins
	(*ChartAxes)(nil),          // 4: render.ChartAxes
	(*ChartView)(nil),          // 5: render.ChartView
}
var file_renderer_service_proto_depIdxs = []int32{
	2, // 0: render.RenderChartRequest.sizes:type_name -> render.ChartSizes
	3, // 1: render.RenderChartRequest.margins:type_name -> render.ChartMargins
	4, // 2: render.RenderChartRequest.axes:type_name -> render.ChartAxes
	5, // 3: render.RenderChartRequest.views:type_name -> render.ChartView
	0, // 4: render.ChartRenderer.RenderChart:input_type -> render.RenderChartRequest
	1, // 5: render.ChartRenderer.RenderChart:output_type -> render.RenderChartReply
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_renderer_service_proto_init() }
func file_renderer_service_proto_init() {
	if File_renderer_service_proto != nil {
		return
	}
	file_chart_proto_init()
	file_view_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_renderer_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderChartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_renderer_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderChartReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_renderer_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_renderer_service_proto_goTypes,
		DependencyIndexes: file_renderer_service_proto_depIdxs,
		MessageInfos:      file_renderer_service_proto_msgTypes,
	}.Build()
	File_renderer_service_proto = out.File
	file_renderer_service_proto_rawDesc = nil
	file_renderer_service_proto_goTypes = nil
	file_renderer_service_proto_depIdxs = nil
}
